import { UserProfile, FinancialGoal, PersonalGoal, AIInsight, Transaction } from './types';

const today = new Date();
const oneWeekAgo = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7);
const twoWeeksAgo = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 14);
const threeWeeksAgo = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 21);

export const userProfile: UserProfile = {
  income: 3200,
  housingCost: 1150,
};

export const financialGoals: FinancialGoal[] = [
  {
    id: 'fin1',
    status: 'active',
    itemName: 'High-End Gaming PC',
    targetAmount: 2500,
    targetDate: '6 months',
    currentAmount: 750,
    timelineAnalysis: 'Your goal is ambitious but achievable. Consistent savings will be key.',
    weeklySavingsTarget: 96,
    savingsHistory: [
      { week: 1, amount: 100 },
      { week: 2, amount: 90 },
      { week: 3, amount: 110 },
      { week: 4, amount: 85 },
      { week: 5, amount: 120 },
      { week: 6, amount: 95 },
      { week: 7, amount: 100 },
    ],
  },
  {
    id: 'fin2',
    status: 'completed',
    itemName: 'Holiday to Japan',
    targetAmount: 3000,
    targetDate: '1 year',
    currentAmount: 3000,
    timelineAnalysis: 'Successfully planned and saved. Well done!',
    weeklySavingsTarget: 58,
    savingsHistory: Array.from({ length: 52 }, (_, i) => ({ week: i + 1, amount: 58 + (Math.random() * 10 - 5) })),
  },
  {
    id: 'fin3',
    status: 'paused',
    itemName: 'New Car Downpayment',
    targetAmount: 5000,
    targetDate: '2 years',
    currentAmount: 1200,
    timelineAnalysis: 'A long-term goal that requires steady contribution. Paused for now.',
    weeklySavingsTarget: 48,
    savingsHistory: Array.from({ length: 25 }, (_, i) => ({ week: i + 1, amount: 48 })),
  },
  {
    id: 'fin4',
    status: 'active',
    itemName: 'Emergency Fund',
    targetAmount: 8000,
    targetDate: '18 months',
    currentAmount: 2400,
    timelineAnalysis: 'Building an emergency fund is crucial for financial security. You\'re making steady progress.',
    weeklySavingsTarget: 85,
    savingsHistory: [
      { week: 1, amount: 100 },
      { week: 2, amount: 85 },
      { week: 3, amount: 90 },
      { week: 4, amount: 80 },
      { week: 5, amount: 95 },
      { week: 6, amount: 85 },
      { week: 7, amount: 100 },
      { week: 8, amount: 75 },
      { week: 9, amount: 90 },
      { week: 10, amount: 85 },
    ],
  },
  {
    id: 'fin5',
    status: 'active',
    itemName: 'Home Studio Equipment',
    targetAmount: 1800,
    targetDate: '4 months',
    currentAmount: 450,
    timelineAnalysis: 'Perfect timing to invest in your creative pursuits. Break it down into smaller purchases.',
    weeklySavingsTarget: 84,
    savingsHistory: [
      { week: 1, amount: 90 },
      { week: 2, amount: 80 },
      { week: 3, amount: 85 },
      { week: 4, amount: 95 },
      { week: 5, amount: 100 },
    ],
  },
  {
    id: 'fin6',
    status: 'active',
    itemName: 'Professional Development Course',
    targetAmount: 800,
    targetDate: '2 months',
    currentAmount: 320,
    timelineAnalysis: 'Investing in yourself is always worthwhile. This timeline is very achievable.',
    weeklySavingsTarget: 60,
    savingsHistory: [
      { week: 1, amount: 80 },
      { week: 2, amount: 60 },
      { week: 3, amount: 70 },
      { week: 4, amount: 55 },
      { week: 5, amount: 55 },
    ],
  },
];

export const personalGoals: PersonalGoal[] = [
  {
    id: 'per1',
    status: 'active',
    goalType: 'Learning',
    dailyTimeAvailable: '45 minutes',
    description: 'Learn to play the guitar',
    targetDate: '6 months',
    currentLevel: 'Beginner',
    timelineAnalysis: 'Learning an instrument requires consistent practice. Focus on fundamentals first.',
    taskHistory: [
      [{ id: 't1a', description: 'Practice C and G chords for 15 minutes', completed: true }, { id: 't1b', description: 'Learn the parts of the guitar', completed: true }, { id: 't1c', description: 'Watch a beginner tutorial on strumming', completed: true }],
      [{ id: 't2a', description: 'Practice switching between C, G, and D chords', completed: true }, { id: 't2b', description: 'Learn a simple 3-chord song', completed: false }, { id: 't2c', description: 'Practice for 30 minutes straight', completed: true }],
      [{ id: 't3a', description: 'Master the E minor chord', completed: true }, { id: 't3b', description: 'Practice "Wonderwall" intro riff', completed: true }, { id: 't3c', description: 'Tune the guitar by ear', completed: false }],
      [{ id: 't4a', description: 'Learn the F chord barre', completed: false }, { id: 't4b', description: 'Practice a major scale', completed: false }, { id: 't4c', description: 'Record yourself playing and listen back', completed: false }],
    ],
    currentWeek: 4,
    completionHistory: [
      { week: 1, completedTasks: 3, totalTasks: 3 },
      { week: 2, completedTasks: 2, totalTasks: 3 },
      { week: 3, completedTasks: 2, totalTasks: 3 },
    ],
  },
  {
    id: 'per2',
    status: 'completed',
    goalType: 'Fitness',
    dailyTimeAvailable: '30 minutes',
    description: 'Run a 5k race',
    targetDate: '3 months',
    currentLevel: 'Beginner',
    timelineAnalysis: 'A great fitness goal. Gradual progression is the safest way to avoid injury.',
    taskHistory: Array.from({ length: 12 }, () => [{ id: crypto.randomUUID(), description: 'Run 3 times this week', completed: true }, { id: crypto.randomUUID(), description: 'Do one session of cross-training', completed: true }]),
    currentWeek: 12,
    completionHistory: Array.from({ length: 12 }, (_, i) => ({ week: i + 1, completedTasks: 2, totalTasks: 2 })),
  },
  {
    id: 'per3',
    status: 'paused',
    goalType: 'Creative',
    dailyTimeAvailable: '1 hour',
    description: 'Write a short story',
    targetDate: '1 month',
    currentLevel: 'Intermediate',
    timelineAnalysis: 'Creative goals can be tough. Setting a word count target can help.',
    taskHistory: [
      [{ id: 'ts1', description: 'Outline the plot points', completed: true }, { id: 'ts2', description: 'Write character bios', completed: true }],
    ],
    currentWeek: 2,
    completionHistory: [{ week: 1, completedTasks: 2, totalTasks: 2}],
  },
  {
    id: 'per4',
    status: 'active',
    goalType: 'Learning',
    dailyTimeAvailable: '1 hour',
    description: 'Master Python programming',
    targetDate: '4 months',
    currentLevel: 'Intermediate',
    timelineAnalysis: 'Building on your existing knowledge is smart. Focus on practical projects to solidify concepts.',
    taskHistory: [
      [{ id: 'py1a', description: 'Complete 3 LeetCode problems', completed: true }, { id: 'py1b', description: 'Read about decorators and context managers', completed: true }, { id: 'py1c', description: 'Build a simple CLI tool', completed: true }],
      [{ id: 'py2a', description: 'Learn about async/await patterns', completed: true }, { id: 'py2b', description: 'Practice with pandas data manipulation', completed: true }, { id: 'py2c', description: 'Create a REST API with FastAPI', completed: false }],
      [{ id: 'py3a', description: 'Study design patterns in Python', completed: true }, { id: 'py3b', description: 'Build a web scraper', completed: true }, { id: 'py3c', description: 'Write unit tests for previous projects', completed: false }],
      [{ id: 'py4a', description: 'Learn about Python packaging', completed: false }, { id: 'py4b', description: 'Contribute to an open source project', completed: false }, { id: 'py4c', description: 'Build a machine learning model', completed: false }],
    ],
    currentWeek: 4,
    completionHistory: [
      { week: 1, completedTasks: 3, totalTasks: 3 },
      { week: 2, completedTasks: 2, totalTasks: 3 },
      { week: 3, completedTasks: 2, totalTasks: 3 },
    ],
  },
  {
    id: 'per5',
    status: 'active',
    goalType: 'Fitness',
    dailyTimeAvailable: '45 minutes',
    description: 'Build strength and muscle',
    targetDate: '6 months',
    currentLevel: 'Beginner',
    timelineAnalysis: 'Strength training requires consistency and progressive overload. Start with compound movements.',
    taskHistory: [
      [{ id: 'st1a', description: 'Full body workout 3x this week', completed: true }, { id: 'st1b', description: 'Learn proper squat form', completed: true }, { id: 'st1c', description: 'Track protein intake daily', completed: true }],
      [{ id: 'st2a', description: 'Increase weights by 5lbs on main lifts', completed: true }, { id: 'st2b', description: 'Add 10 minutes of stretching after workouts', completed: false }, { id: 'st2c', description: 'Meal prep for the week', completed: true }],
      [{ id: 'st3a', description: 'Master deadlift technique', completed: false }, { id: 'st3b', description: 'Complete 4 workouts this week', completed: false }, { id: 'st3c', description: 'Take progress photos', completed: false }],
    ],
    currentWeek: 3,
    completionHistory: [
      { week: 1, completedTasks: 3, totalTasks: 3 },
      { week: 2, completedTasks: 2, totalTasks: 3 },
    ],
  },
  {
    id: 'per6',
    status: 'active',
    goalType: 'Creative',
    dailyTimeAvailable: '30 minutes',
    description: 'Learn digital art and illustration',
    targetDate: '5 months',
    currentLevel: 'Beginner',
    timelineAnalysis: 'Digital art has a learning curve, but daily practice will build your skills quickly.',
    taskHistory: [
      [{ id: 'art1a', description: 'Complete basic shapes and lines exercises', completed: true }, { id: 'art1b', description: 'Watch 2 digital art tutorials', completed: true }, { id: 'art1c', description: 'Set up drawing tablet and software', completed: true }],
      [{ id: 'art2a', description: 'Practice gesture drawing for 20 minutes daily', completed: true }, { id: 'art2b', description: 'Complete a simple character sketch', completed: false }, { id: 'art2c', description: 'Study color theory basics', completed: true }],
      [{ id: 'art3a', description: 'Draw from photo references', completed: false }, { id: 'art3b', description: 'Experiment with different brushes', completed: false }, { id: 'art3c', description: 'Join an online art community', completed: false }],
    ],
    currentWeek: 3,
    completionHistory: [
      { week: 1, completedTasks: 3, totalTasks: 3 },
      { week: 2, completedTasks: 2, totalTasks: 3 },
    ],
  },
  {
    id: 'per7',
    status: 'active',
    goalType: 'Learning',
    dailyTimeAvailable: '20 minutes',
    description: 'Learn Spanish conversational skills',
    targetDate: '8 months',
    currentLevel: 'Beginner',
    timelineAnalysis: 'Language learning benefits from daily practice. Focus on speaking from day one.',
    taskHistory: [
      [{ id: 'sp1a', description: 'Complete Duolingo lesson daily', completed: true }, { id: 'sp1b', description: 'Learn 20 new vocabulary words', completed: true }, { id: 'sp1c', description: 'Practice pronunciation with audio', completed: true }],
      [{ id: 'sp2a', description: 'Have 5-minute conversation with language partner', completed: false }, { id: 'sp2b', description: 'Watch Spanish YouTube videos with subtitles', completed: true }, { id: 'sp2c', description: 'Write a short paragraph in Spanish', completed: true }],
      [{ id: 'sp3a', description: 'Learn present tense conjugations', completed: false }, { id: 'sp3b', description: 'Practice ordering food in Spanish', completed: false }, { id: 'sp3c', description: 'Listen to Spanish podcast for beginners', completed: false }],
    ],
    currentWeek: 3,
    completionHistory: [
      { week: 1, completedTasks: 3, totalTasks: 3 },
      { week: 2, completedTasks: 2, totalTasks: 3 },
    ],
  },
  {
    id: 'per8',
    status: 'active',
    goalType: 'Health',
    dailyTimeAvailable: '15 minutes',
    description: 'Establish a meditation practice',
    targetDate: '2 months',
    currentLevel: 'Beginner',
    timelineAnalysis: 'Meditation is about consistency over duration. Start small and build the habit.',
    taskHistory: [
      [{ id: 'med1a', description: 'Meditate for 5 minutes daily', completed: true }, { id: 'med1b', description: 'Try 3 different meditation apps', completed: true }, { id: 'med1c', description: 'Read about mindfulness basics', completed: true }],
      [{ id: 'med2a', description: 'Increase to 10 minutes daily', completed: true }, { id: 'med2b', description: 'Practice breathing exercises', completed: false }, { id: 'med2c', description: 'Meditate at the same time each day', completed: true }],
      [{ id: 'med3a', description: 'Try walking meditation', completed: false }, { id: 'med3b', description: 'Join a meditation group or class', completed: false }, { id: 'med3c', description: 'Track mood before and after sessions', completed: false }],
    ],
    currentWeek: 3,
    completionHistory: [
      { week: 1, completedTasks: 3, totalTasks: 3 },
      { week: 2, completedTasks: 2, totalTasks: 3 },
    ],
  },
];

export const insights: AIInsight[] = [
  {
    id: 'ins1',
    type: 'cross-goal',
    text: "It looks like your personal goal progress dipped the same week your savings were lower. Is there a connection between your energy levels and your spending habits?",
    date: twoWeeksAgo.toISOString(),
  },
  {
    id: 'ins2',
    type: 'motivational',
    text: "You've been incredibly consistent with your guitar practice! That dedication is powerful. Apply that same focus to your savings this week and see what happens.",
    date: oneWeekAgo.toISOString(),
  },
  {
    id: 'ins3',
    type: 'financial',
    text: "Great job hitting your savings target last week! You're building strong momentum toward that gaming PC.",
    date: today.toISOString(),
  },
  {
    id: 'ins4',
    type: 'personal',
    text: "Your Python learning is accelerating! You're completing more complex tasks each week. Consider starting a side project to apply these skills.",
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1).toISOString(),
  },
  {
    id: 'ins5',
    type: 'cross-goal',
    text: "I notice you're saving for both a gaming PC and studio equipment. These complement each other well - consider if there's overlap in what you need.",
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3).toISOString(),
  },
  {
    id: 'ins6',
    type: 'motivational',
    text: "Your meditation practice is building a strong foundation. The consistency you're showing here is impressive and will benefit all your other goals.",
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 4).toISOString(),
  },
  {
    id: 'ins7',
    type: 'financial',
    text: "Your emergency fund progress is steady and responsible. This foundation will give you confidence to pursue other goals more aggressively.",
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 6).toISOString(),
  },
  {
    id: 'ins8',
    type: 'personal',
    text: "You're tackling multiple learning goals simultaneously. Consider if focusing on 2-3 at a time might accelerate your progress.",
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 8).toISOString(),
  },
  {
    id: 'ins9',
    type: 'cross-goal',
    text: "Your fitness and meditation goals are synergistic. The discipline from one reinforces the other. Keep this momentum going!",
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 10).toISOString(),
  },
  {
    id: 'ins10',
    type: 'financial',
    text: "Investing in your professional development course shows great foresight. The skills you gain could accelerate your earning potential.",
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 12).toISOString(),
  },
];

export const transactions: Transaction[] = [
  { id: 'tx1', description: 'Monthly Salary', amount: 3200, type: 'income', category: 'Salary', date: new Date(today.getFullYear(), today.getMonth(), 1).toISOString() },
  { id: 'tx2', description: 'Weekly Groceries', amount: 85.50, type: 'expense', category: 'Food', date: oneWeekAgo.toISOString() },
  { id: 'tx3', description: 'Dinner with friends', amount: 45.00, type: 'expense', category: 'Social', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5).toISOString() },
  { id: 'tx4', description: 'Train ticket', amount: 12.80, type: 'expense', category: 'Transport', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3).toISOString() },
  { id: 'tx5', description: 'Spotify Subscription', amount: 9.99, type: 'expense', category: 'Subscriptions', date: new Date(today.getFullYear(), today.getMonth(), 5).toISOString() },
  { id: 'tx6', description: 'New video game', amount: 59.99, type: 'expense', category: 'Entertainment', date: twoWeeksAgo.toISOString() },
  { id: 'tx7', description: 'Freelance Work Payment', amount: 250, type: 'income', category: 'Freelance', date: twoWeeksAgo.toISOString() },
  { id: 'tx8', description: 'Coffee', amount: 3.50, type: 'expense', category: 'Food', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2).toISOString() },
  { id: 'tx9', description: 'Gym Membership', amount: 40.00, type: 'expense', category: 'Health', date: new Date(today.getFullYear(), today.getMonth(), 2).toISOString() },
  { id: 'tx10', description: 'Internet Bill', amount: 35.00, type: 'expense', category: 'Utilities', date: new Date(today.getFullYear(), today.getMonth(), 10).toISOString() },
  { id: 'tx11', description: 'Freelance Design Project', amount: 450, type: 'income', category: 'Freelance', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1).toISOString() },
  { id: 'tx12', description: 'Drawing Tablet', amount: 120, type: 'expense', category: 'Equipment', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2).toISOString() },
  { id: 'tx13', description: 'Spanish Learning App Subscription', amount: 12.99, type: 'expense', category: 'Education', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 4).toISOString() },
  { id: 'tx14', description: 'Meditation App Premium', amount: 8.99, type: 'expense', category: 'Health', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 6).toISOString() },
  { id: 'tx15', description: 'Guitar Strings & Picks', amount: 25.50, type: 'expense', category: 'Hobbies', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7).toISOString() },
  { id: 'tx16', description: 'Programming Books', amount: 65.00, type: 'expense', category: 'Education', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 9).toISOString() },
  { id: 'tx17', description: 'Protein Powder', amount: 35.99, type: 'expense', category: 'Health', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 11).toISOString() },
  { id: 'tx18', description: 'Online Course - Python Advanced', amount: 89.99, type: 'expense', category: 'Education', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 13).toISOString() },
  { id: 'tx19', description: 'Art Supplies', amount: 42.75, type: 'expense', category: 'Hobbies', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 15).toISOString() },
  { id: 'tx20', description: 'Lunch Meeting', amount: 28.50, type: 'expense', category: 'Social', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 16).toISOString() },
  { id: 'tx21', description: 'Bus Pass Monthly', amount: 75.00, type: 'expense', category: 'Transport', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 18).toISOString() },
  { id: 'tx22', description: 'Consulting Work', amount: 320, type: 'income', category: 'Freelance', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 20).toISOString() },
  { id: 'tx23', description: 'Grocery Shopping', amount: 92.30, type: 'expense', category: 'Food', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 21).toISOString() },
  { id: 'tx24', description: 'Netflix Subscription', amount: 15.99, type: 'expense', category: 'Subscriptions', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 22).toISOString() },
  { id: 'tx25', description: 'Yoga Class Drop-in', amount: 20.00, type: 'expense', category: 'Health', date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 24).toISOString() },
];


export const demoData = {
    userProfile,
    financialGoals,
    personalGoals,
    insights,
    transactions
};
